// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvqhvzmmvcjdooubsgpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cWh2em1tdmNqZG9vdWJzZ3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODc3ODAsImV4cCI6MjA2NTU2Mzc4MH0.pmpARYafwgunU8d96Vg_5sIOoiiYnMmm_0H-g2eW4vI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);